name: Deploy App Spec Changes

on:
  push:
    branches:
      - main
    paths:
    - 'deployments/app_spec.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install DigitalOcean CLI
        run: |
          sudo snap install doctl 
          doctl auth init --access-token="${{ secrets.DIGITALOCEAN_API_TOKEN }}"

      - name: Update App Spec
        run: |
          doctl apps update  598a4c86-8a4c-4467-99a6-c037fd63fd87    --spec deployments/app_spec.yaml

      - name: Verify Deployment
        run: doctl apps get  598a4c86-8a4c-4467-99a6-c037fd63fd87               
