name: Deploy App Spec Changes

on:
  push:
    branches:
      - main
    paths:
    - 'deployments/app_spec.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install DigitalOcean CLI
        run: |
          sudo snap install doctl 
          doctl auth init --access-token="${{ secrets.DIGITALOCEAN_API_TOKEN }}"

      - name: Update App Spec
        run: |
          doctl apps update  70f58411-66ed-4cc0-9fff-c758d97c76c5   --spec deployments/app_spec.yaml

      - name: Verify Deployment
        run: doctl apps get  70f58411-66ed-4cc0-9fff-c758d97c76c5              
